### ISSUE TITLE
feat: ✨ React component support

### ISSUE THREAD

**Issue by klaarseSICKAG** [SickDesignSystem/synergy#43]
**Description**:

As a developer using Synergy, I want to be able to use the components in my React applications with correct intelli-sense, event and attribute handling.

**Rationale**:

Better DX for React developers.

**Comment by schilchSICKAG** [comment]
Will be done after the setup in #60. `make-react.js´ will have to be adjusted to the following:

- [ ] Create a new package `@synergy-design-system/react`
- [ ] Bootstrap the package
- [ ] Adjust `make-react.js` to use the given path. We will also have to copy or otherwise link some internal shoelace-scripts (like `events.ts`
- [ ] Test in a real world react application.
