### ISSUE TITLE
feat: ✨ Use Linting/Formatting etc. in components package/with Shoelace CLI

### ISSUE THREAD

**Issue by mariohamann** [SickDesignSystem/synergy#58]
---

## User Story
As a developer I need the same linting and formatting rules for Shoelace as otherwise we will get lots of conflicts etc. in future.

## Description
There are different alternatives: 
1. Use Shoelace's rules – if we use them, should we update them automatically (and extend the CLI accordingly)?
3. Use own rules and update the vendor folder accordingly

**Comment by kirchsuSICKAG** [comment]
### Notes for alternative 1:
If using the eslint config from shoelace we have following problem:
We can`t exactly use the shoelace config like it is. We are getting several errors. 
For example because of the renaming of classes and files, we have the problem, that the alphabetic sorting of imports is no longer correct.  (e.g. alert.component.ts: ShoelaceElement -> SickElement, SlIconButton --> SdsIconButton, therefore the sorting is no longer correct).

Additionally we are getting errors in the automatically generated stories. They don`t fit in the shoelace linting rules and therefore the eslint config needs to be updated. 

The needed added config for the shoelace eslint is following:
![image](https://github.com/SickDesignSystem/sds/assets/115139104/04e23a36-af44-4cef-be71-6c6b955b2a1b)


### Notes for alternative 2:
If we are using our rules and let automatically run a --fix over the vendor folder, we will still have 224 errors and 44 warning.
![image](https://github.com/SickDesignSystem/sds/assets/115139104/077c2e0d-eb2f-4947-ac02-84cad8339ff5)

To get rid of the other errors we need to add following rules to the eslint config:
![image](https://github.com/SickDesignSystem/sds/assets/115139104/85e5d368-0755-44fe-bf1e-2fd9a0703e92)

**Comment by kirchsuSICKAG** [comment]
no, unfortunately not. But if we adjust following files a little bit (`.storybook/helper.ts`, `scripts/basics/create-storybook-files.js`) we are able to get rid of all errors with the auto fix.

**Comment by mariohamann** [comment]
Perfect. As this is stuff we totally have under control, whit looks like a valid path from my perspective

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
